stages:
  - maventry
  - androidtry
  - mavenDeploy

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend/BackendCode
    - mvn package

# android-build: #this is another job
#   image: gjandres/android-ci:latest      # this is a directive to DOCKER
#   stage: androidtry
#   tags:
#    - android_tag         #this is LINK to the docker runner on the remote-server        
#   before_script:
#     - export GRADLE_USER_HOME=`pwd`/.gradle
#     - chmod +x ./Frontend/NovelloApp/gradlew
#   script:
#     - cd Frontend/NovelloApp
#     - ./gradlew assemble
  
autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - springboot_tag
  only:
    refs:
      - main
  script:
    - cd Backend/BackendCode
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
